"use client";

import { useState, type FormEvent } from "react";

interface Entry { action: string; actorId: string; id: string; result: string; targetId: string; targetType: string; timestamp: string }

export function AuditClient() {
  const [entries, setEntries] = useState<readonly Entry[]>([]); const [cursor, setCursor] = useState<string>(); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [searched, setSearched] = useState(false);
  const load = async (nextQuery: string) => { if (loading) return; setLoading(true); setError(""); try { const response = await fetch(`/api/v1/admin/audit?${nextQuery}`, { cache: "no-store" }); if (!response.ok) throw new Error("No fue posible consultar la auditoría."); const page = await response.json() as { cursor?: string; entries: readonly Entry[] }; setEntries((current) => nextQuery.includes("cursor=") ? [...current, ...page.entries] : page.entries); setCursor(page.cursor); setSearched(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible consultar la auditoría."); } finally { setLoading(false); } };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const fromDate = String(data.get("from")); const toDate = String(data.get("to")); const actorId = String(data.get("actorId") ?? "").trim(); const params = new URLSearchParams({ actorId, from: `${fromDate}T00:00:00Z`, mode: "ACTOR", to: `${toDate}T23:59:59Z` }); setQuery(params.toString()); setCursor(undefined); void load(params.toString()); };
  return <section><p className="text-sm font-bold uppercase tracking-wide text-accent">Administración</p><h1 className="mt-2 text-3xl font-black">Auditoría</h1><p className="mt-3 text-muted">Registros inmutables y sanitizados. Solo administradores.</p><form className="mt-8 grid gap-4 sm:grid-cols-3" onSubmit={submit}><label className="font-bold">Actor<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" name="actorId" required /></label><label className="font-bold">Desde<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" name="from" required type="date" /></label><label className="font-bold">Hasta<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" name="to" required type="date" /></label><button className="min-h-11 rounded-lg bg-brand-900 px-5 font-bold text-white disabled:opacity-60 sm:col-span-3" disabled={loading} type="submit">{loading ? "Consultando…" : "Consultar"}</button></form><p aria-live="assertive" className="mt-4 font-semibold text-red-700">{error}</p>{searched && entries.length === 0 ? <p className="mt-8 rounded-xl border border-dashed p-6 text-center">No hay acciones para el rango solicitado.</p> : <ul className="mt-8 grid gap-3">{entries.map((entry) => <li className="rounded-xl border bg-surface p-4" key={entry.id}><strong>{entry.action}</strong><p>{entry.timestamp} · {entry.result}</p><p className="text-sm text-muted">{entry.targetType} / {entry.targetId}</p></li>)}</ul>}{cursor !== undefined ? <button className="mt-5 min-h-11 rounded-lg border px-5 font-bold disabled:opacity-60" disabled={loading} onClick={() => void load(`${query}&cursor=${encodeURIComponent(cursor)}`)} type="button">Cargar más</button> : null}</section>;
}
