"use client";

import { useState, type FormEvent } from "react";

interface Asset { readonly id: string; readonly publicObjectKey?: string; readonly status: string; readonly version: number }
const message = async (response: Response): Promise<string> => { try { return ((await response.json()) as { message?: string }).message ?? "La operación no pudo completarse."; } catch { return "La operación no pudo completarse."; } };

export function AdminGalleryClient() {
  const [asset, setAsset] = useState<Asset>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = async (id: string) => { setBusy(true); setError(""); try { const response = await fetch(`/api/v1/admin/gallery/assets/${encodeURIComponent(id)}`, { cache: "no-store" }); if (!response.ok) throw new Error(await message(response)); setAsset(await response.json() as Asset); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos consultar la imagen."); } finally { setBusy(false); } };
  const find = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const id = String(new FormData(event.currentTarget).get("assetId") ?? "").trim(); if (!busy) void load(id); };
  const mutate = async (operation: "HIDE" | "PUBLISH", form?: HTMLFormElement) => { if (asset === undefined || busy) return; setBusy(true); setError(""); setSuccess(""); const data = form === undefined ? undefined : new FormData(form); try { let consentId: string | undefined; if (operation === "PUBLISH") { const consentResponse = await fetch("/api/v1/admin/gallery/consents", { body: JSON.stringify({ assetId: asset.id, grantedBy: String(data?.get("grantedBy") ?? ""), status: "GRANTED" }), headers: { "content-type": "application/json" }, method: "POST" }); if (!consentResponse.ok) throw new Error(await message(consentResponse)); consentId = ((await consentResponse.json()) as { id: string }).id; } const response = await fetch(`/api/v1/admin/gallery/assets/${encodeURIComponent(asset.id)}`, { body: JSON.stringify(operation === "HIDE" ? { expectedVersion: asset.version, operation } : { consentId, expectedVersion: asset.version, operation, publicObjectKey: String(data?.get("publicObjectKey") ?? asset.publicObjectKey ?? "") }), headers: { "content-type": "application/json" }, method: "PATCH" }); if (!response.ok) throw new Error(await message(response)); setAsset(await response.json() as Asset); setSuccess(operation === "HIDE" ? "Imagen ocultada." : "Imagen publicada."); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos actualizar la imagen."); } finally { setBusy(false); } };
  return <div><header><p className="text-sm font-bold uppercase tracking-wide text-accent">Administración</p><h1 className="mt-2 text-3xl font-black">Galería</h1><p className="mt-3 text-muted">Publica solo derivados con consentimiento vigente. Los originales nunca son públicos.</p></header><form className="mt-8 flex flex-col gap-3 sm:flex-row" onSubmit={find}><label className="grow font-bold">Identificador del activo<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" name="assetId" required /></label><button className="min-h-11 self-end rounded-lg bg-brand-900 px-5 font-bold text-white disabled:opacity-60" disabled={busy} type="submit">{busy ? "Consultando…" : "Consultar"}</button></form><p aria-live="assertive" className="mt-4 font-semibold text-red-700">{error}</p><p aria-live="polite" className="mt-4 font-semibold text-emerald-700">{success}</p>{asset === undefined ? <p className="mt-8 rounded-xl border border-dashed border-slate-400 p-6 text-center text-muted">Consulta un activo procesado para administrarlo.</p> : <section className="mt-8 rounded-2xl border border-black/10 bg-surface p-5"><h2 className="text-xl font-black">Activo {asset.id}</h2><p className="mt-2">Estado: <strong>{asset.status}</strong></p>{asset.status === "READY" || asset.status === "HIDDEN" ? <form className="mt-5 grid gap-3" onSubmit={(event) => { event.preventDefault(); void mutate("PUBLISH", event.currentTarget); }}><label className="font-bold">Alumno o responsable que otorgó consentimiento<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" name="grantedBy" required /></label><label className="font-bold">Clave del derivado<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={asset.publicObjectKey} name="publicObjectKey" required /></label><button className="min-h-11 rounded-lg bg-accent px-4 font-bold disabled:opacity-60" disabled={busy} type="submit">Publicar</button></form> : null}{asset.status === "PUBLISHED" ? <button className="mt-5 min-h-11 rounded-lg border border-red-700 px-4 font-bold text-red-800 disabled:opacity-60" disabled={busy} onClick={() => void mutate("HIDE")} type="button">Ocultar</button> : null}</section>}</div>;
}
