"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";

type Kind = "class-types" | "trainers";
type Status = "ACTIVE" | "INACTIVE";
interface CatalogItem { readonly bio?: string; readonly description?: string; readonly id: string; readonly name: string; readonly status: Status; readonly version: number }
interface CatalogPage { readonly capabilities: { readonly canManage: boolean }; readonly cursor?: string; readonly items: readonly CatalogItem[] }
interface ApiFailure { readonly message?: string }
const labels = { "class-types": { empty: "No hay tipos de clase", item: "Tipo de clase", title: "Tipos de clase" }, trainers: { empty: "No hay entrenadores", item: "Entrenador", title: "Entrenadores" } } as const;
const failure = async (response: Response): Promise<string> => { try { return ((await response.json()) as ApiFailure).message ?? "La operación no pudo completarse."; } catch { return "La operación no pudo completarse."; } };

export function AdminClassCatalogClient() {
  return <div><header><p className="text-sm font-bold uppercase tracking-wide text-accent">Administración</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Entrenadores y clases</h1><p className="mt-3 max-w-3xl leading-7 text-muted">Las bajas son lógicas: las sesiones históricas conservan sus nombres e identificadores.</p></header><div className="mt-8 grid gap-10 xl:grid-cols-2"><CatalogSection kind="trainers" /><CatalogSection kind="class-types" /></div></div>;
}

function CatalogSection({ kind }: { readonly kind: Kind }) {
  const [page, setPage] = useState<CatalogPage>(); const [status, setStatus] = useState<Status | "ALL">("ALL");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const load = useCallback(async (filter: Status | "ALL", cursor?: string) => { setLoading(true); setError(""); const params = new URLSearchParams({ status: filter }); if (cursor !== undefined) params.set("cursor", cursor); try { const response = await fetch(`/api/v1/admin/${kind}?${params}`, { cache: "no-store" }); if (!response.ok) throw new Error(await failure(response)); const result = await response.json() as CatalogPage; setPage((current) => cursor === undefined ? result : { ...result, items: [...(current?.items ?? []), ...result.items] }); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "No pudimos consultar el catálogo."); } finally { setLoading(false); } }, [kind]);
  useEffect(() => { const timeout = window.setTimeout(() => void load("ALL"), 0); return () => window.clearTimeout(timeout); }, [load]);
  const create = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy !== "") return; const form = event.currentTarget; const data = new FormData(form); setBusy("new"); setError(""); setSuccess(""); try { const response = await fetch(`/api/v1/admin/${kind}`, { body: JSON.stringify({ description: String(data.get("description") ?? ""), name: String(data.get("name") ?? "") }), headers: { "content-type": "application/json" }, method: "POST" }); if (!response.ok) throw new Error(await failure(response)); form.reset(); setSuccess(`${labels[kind].item} creado correctamente.`); await load(status); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "No pudimos crear el elemento."); } finally { setBusy(""); } };
  const update = async (event: FormEvent<HTMLFormElement>, item: CatalogItem) => { event.preventDefault(); if (busy !== "") return; const data = new FormData(event.currentTarget); setBusy(item.id); setError(""); setSuccess(""); try { const response = await fetch(`/api/v1/admin/${kind}/${encodeURIComponent(item.id)}`, { body: JSON.stringify({ description: String(data.get("description") ?? ""), expectedVersion: item.version, name: String(data.get("name") ?? ""), status: String(data.get("status")) }), headers: { "content-type": "application/json" }, method: "PATCH" }); if (!response.ok) throw new Error(await failure(response)); setSuccess("Cambios guardados."); await load(status); } catch (reason: unknown) { setError(reason instanceof Error ? reason.message : "No pudimos actualizar el elemento."); } finally { setBusy(""); } };
  return <section aria-labelledby={`${kind}-title`}><h2 className="text-2xl font-black" id={`${kind}-title`}>{labels[kind].title}</h2><div className="mt-4 flex gap-3"><label className="grow font-bold">Mostrar<select className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" value={status} onChange={(event) => setStatus(event.currentTarget.value as Status | "ALL")}><option value="ALL">Todos</option><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option></select></label><button className="min-h-11 self-end rounded-lg border border-brand-900 px-4 font-bold" disabled={loading} onClick={() => void load(status)} type="button">Filtrar</button></div>{page?.capabilities.canManage ? <form className="mt-5 grid gap-3 rounded-2xl border border-black/10 bg-surface p-4" onSubmit={(event) => void create(event)}><h3 className="text-xl font-black">Crear {labels[kind].item.toLocaleLowerCase("es")}</h3><CatalogFields prefix={`new-${kind}`} /><button className="min-h-11 rounded-lg bg-brand-900 px-4 font-bold text-white disabled:opacity-60" disabled={busy !== ""} type="submit">{busy === "new" ? "Creando…" : "Crear"}</button></form> : null}<p aria-live="polite" className="mt-3 font-semibold text-emerald-700">{success}</p><p aria-live="assertive" className="mt-2 font-semibold text-red-700">{error}</p>{loading && page === undefined ? <p className="py-10 text-center">Cargando…</p> : page === undefined || page.items.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-slate-400 p-6 text-center text-muted">{labels[kind].empty}</p> : <ul className="mt-5 grid gap-3">{page.items.map((item) => <li className="rounded-xl border border-black/10 bg-surface p-4" key={item.id}><div className="flex justify-between gap-3"><h3 className="text-lg font-black">{item.name}</h3><span className="text-sm font-bold">{item.status === "ACTIVE" ? "Activo" : "Inactivo"}</span></div>{page.capabilities.canManage ? <form className="mt-3 grid gap-3" onSubmit={(event) => void update(event, item)}><CatalogFields item={item} prefix={`${kind}-${item.id}`} /><label className="font-bold">Estado<select className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={item.status} name="status"><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo (baja lógica)</option></select></label><button className="min-h-11 rounded-lg bg-accent px-4 font-bold disabled:opacity-60" disabled={busy !== ""} type="submit">{busy === item.id ? "Guardando…" : "Guardar"}</button></form> : <p className="mt-2 text-muted">{item.bio ?? item.description ?? "Sin descripción."}</p>}</li>)}</ul>}{page?.cursor === undefined ? null : <button className="mt-5 min-h-11 rounded-lg border border-brand-900 px-4 font-bold" disabled={loading} onClick={() => void load(status, page.cursor)} type="button">Cargar más</button>}</section>;
}

function CatalogFields({ item, prefix }: { readonly item?: CatalogItem; readonly prefix: string }) {
  return <><label className="font-bold" htmlFor={`name-${prefix}`}>Nombre<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={item?.name} id={`name-${prefix}`} maxLength={120} minLength={2} name="name" required /></label><label className="font-bold" htmlFor={`description-${prefix}`}>Descripción opcional<textarea className="mt-1 min-h-20 w-full rounded-lg border border-slate-400 p-3" defaultValue={item?.bio ?? item?.description} id={`description-${prefix}`} maxLength={500} name="description" /></label></>;
}
