"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

interface Dashboard { readonly links: readonly { readonly description: string; readonly href: string; readonly label: string }[]; readonly role: "ADMIN" | "STAFF" }
export function AdminDashboardClient() {
  const [dashboard, setDashboard] = useState<Dashboard>(); const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/v1/admin/dashboard", { cache: "no-store" }).then(async (response) => { if (!response.ok) { const body = await response.json() as { message?: string }; throw new Error(body.message ?? "No se pudo abrir el panel."); } setDashboard(await response.json() as Dashboard); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "No se pudo abrir el panel.")); }, []);
  return <div><header><p className="text-sm font-bold uppercase tracking-wide text-accent">Administración</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Panel del gimnasio</h1><p className="mt-3 max-w-3xl leading-7 text-muted">Accede a las operaciones habilitadas para tu rol. Cada vista vuelve a comprobar permisos en el backend.</p></header>{error !== "" ? <div className="mt-8 rounded-xl border border-red-300 bg-red-50 p-6" role="alert"><h2 className="font-black">No pudimos cargar el panel</h2><p className="mt-2">{error}</p></div> : dashboard === undefined ? <p aria-live="polite" className="py-16 text-center">Cargando panel…</p> : dashboard.links.length === 0 ? <p className="mt-8 rounded-xl border border-dashed border-slate-400 p-6 text-center">No hay módulos disponibles para tu rol.</p> : <><p className="mt-8 rounded-lg bg-brand-900 px-4 py-3 font-bold text-white" aria-live="polite">Sesión operativa: {dashboard.role === "ADMIN" ? "Administrador" : "Personal"}</p><nav aria-label="Módulos administrativos" className="mt-6"><ul className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{dashboard.links.map((item) => <li key={item.href}><Link className="block h-full rounded-2xl border border-black/10 bg-surface p-5 shadow-sm transition hover:-translate-y-0.5 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand-900" href={item.href}><h2 className="text-xl font-black">{item.label}</h2><p className="mt-2 leading-6 text-muted">{item.description}</p><span className="mt-4 inline-block font-bold text-brand-900">Abrir módulo →</span></Link></li>)}</ul></nav></>}</div>;
}
