"use client";

import { useEffect, useState, type FormEvent } from "react";

interface Settings { cancellationWindowMinutes: number; currency: "PYG"; gymName: string; timezone: "America/Asuncion"; version: number; whatsappNumber?: string }

export function SettingsClient() {
  const [settings, setSettings] = useState<Settings>(); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { void fetch("/api/v1/admin/settings", { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error("No fue posible cargar la configuración."); const value = await response.json() as Settings | null; setSettings(value ?? { cancellationWindowMinutes: 120, currency: "PYG", gymName: "Gym ADR", timezone: "America/Asuncion", version: 0 }); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "No fue posible cargar la configuración.")).finally(() => setLoading(false)); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (busy || settings === undefined) return; setBusy(true); setError(""); setSuccess(""); const data = new FormData(event.currentTarget); const whatsapp = String(data.get("whatsappNumber") ?? "").trim(); const payload = { cancellationWindowMinutes: Number(data.get("cancellationWindowMinutes")), currency: "PYG", ...(settings.version === 0 ? {} : { expectedVersion: settings.version }), gymName: String(data.get("gymName") ?? ""), timezone: "America/Asuncion", ...(whatsapp === "" ? {} : { whatsappNumber: whatsapp }) }; try { const response = await fetch("/api/v1/admin/settings", { body: JSON.stringify(payload), headers: { "content-type": "application/json" }, method: "PUT" }); if (!response.ok) throw new Error(response.status === 409 ? "La configuración cambió; vuelve a cargarla." : "No fue posible guardar la configuración."); setSettings(await response.json() as Settings); setSuccess("Configuración guardada."); } catch (reason) { setError(reason instanceof Error ? reason.message : "No fue posible guardar la configuración."); } finally { setBusy(false); } };
  if (loading) return <p aria-live="polite">Cargando configuración…</p>; if (settings === undefined) return <p role="alert">{error || "No hay configuración disponible."}</p>;
  return <section><p className="text-sm font-bold uppercase tracking-wide text-accent">Administración</p><h1 className="mt-2 text-3xl font-black">Configuración</h1><p className="mt-3 text-muted">Solo se guardan parámetros operativos; nunca secretos.</p><form className="mt-8 grid gap-5" onSubmit={submit}><label className="font-bold">Nombre del gimnasio<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={settings.gymName} name="gymName" required /></label><label className="font-bold">Plazo de cancelación (minutos)<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={settings.cancellationWindowMinutes} max={10080} min={1} name="cancellationWindowMinutes" required type="number" /></label><label className="font-bold">WhatsApp E.164<input className="mt-1 min-h-11 w-full rounded-lg border border-slate-400 px-3" defaultValue={settings.whatsappNumber} name="whatsappNumber" placeholder="+595…" /></label><p>Moneda: <strong>PYG</strong> · Zona horaria: <strong>America/Asuncion</strong></p><button className="min-h-11 rounded-lg bg-brand-900 px-5 font-bold text-white disabled:opacity-60" disabled={busy} type="submit">{busy ? "Guardando…" : "Guardar"}</button></form><p aria-live="assertive" className="mt-4 font-semibold text-red-700">{error}</p><p aria-live="polite" className="mt-4 font-semibold text-emerald-700">{success}</p></section>;
}
